# Generated by Django 3.2.3 on 2021-12-22 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20211101_0823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariantprice',
            name='stock',
            field=models.IntegerField(max_length=11),
        ),
    ]
